// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyFcRk5TV08GDO4qvA-_cMUqHQ6-0ywMY',
    appId: '1:93539988893:web:3297a67a279be66c90ab74',
    messagingSenderId: '93539988893',
    projectId: 'hufs-fc8d8',
    authDomain: 'hufs-fc8d8.firebaseapp.com',
    databaseURL: 'https://hufs-fc8d8-default-rtdb.firebaseio.com',
    storageBucket: 'hufs-fc8d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_jjZXNsoLQPdl6Mp2voQTCk5SNgqHesI',
    appId: '1:93539988893:android:c5cce9fb93db0d8590ab74',
    messagingSenderId: '93539988893',
    projectId: 'hufs-fc8d8',
    databaseURL: 'https://hufs-fc8d8-default-rtdb.firebaseio.com',
    storageBucket: 'hufs-fc8d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx9Uo8_GtMETKF8fGljhwX730zvKPTdeg',
    appId: '1:93539988893:ios:a3ab4921f8235efc90ab74',
    messagingSenderId: '93539988893',
    projectId: 'hufs-fc8d8',
    databaseURL: 'https://hufs-fc8d8-default-rtdb.firebaseio.com',
    storageBucket: 'hufs-fc8d8.appspot.com',
    iosBundleId: 'com.example.hufs',
  );
}
